### ISSUE TITLE
with Android 12, HttpCookie does not get serialized properly with gson.toJson

### ISSUE THREAD

**Issue by faraday** [gotev/android-cookie-store#28] opened 2022-01-07 13:56 UTC
In `SharedPreferencesCookieStore.kt` line 60:
```
gson.toJson(ArrayList(cookies)))
```

This is critical to serialize HttpCookie ArrayList to sharedPreferences.
Only `httpOnly` and `whenCreated` fields appear as BoundFields.
`name` and `value` of the cookie does not get written to prefs.

This bug renders the library useless above Android 12+

**Comment by msteini82** [comment] 2022-02-27 22:40
I encountered the same problem and needed to find a fix, because I need to update my app to Android 12 and use the SharePreferencesCookieStore for my login management.

So I searched for a solution the last two days:

The problem is that with Android 12 Google changed their restrictions for non-sdk interfaces and put most of the fields of HttpCookie class on their blacklist. Look at [Android 12 non-sdk restrictions](https://developer.android.com/about/versions/12/non-sdk-12)

This leads to the problem that the ReflectionTypeAdapter from gson cannot read or write these blacklisted fields anymore, as they are not available for the reflection api.

The solution is to write a custom TypeAdapter for gson, that manually serialize ArrayList<HttpCookie> to a JsonElement and deserialize it backwards. Therefore it is only possible to use the public fields and methods of HttpCookie class to read from or create it.

Another problem here is that the field `whenCreated` is private and has no getter or setter. The correct value in `whenCreated` is important for the correct expireDate, which is calculated in HttpCookie, so we can't skip to set it correct when recreating the cookie. But `whenCreated` is not fully blocked by Android (it's only on the greylist), so that we can use the reflection api to get or set it. This results in a warning in logcat for accessing hidden fields, but it works for now.

As the field is greylisted, Google will not promise that they won't blacklist it on a later release. I didn't find any hints that they change their non-sdk restrictions for Android 13, but it should kept an eye on later releases.

I've written a custom TypeAdapter and tested it in my fork that you @gotev can adapt for your library, look at [my fork](https://github.com/msteini82/android-cookie-store/blob/1.4.1/cookie-store/src/main/java/net/gotev/cookiestore/SharedPreferencesCookieStore.kt)

**Comment by gotev** [comment] 2022-02-27 23:05
@msteini82 thank you for your analysis! 

### my 2 cents
It seems Google is making steps towards their idea of [completely dropping Cookies support on their platforms](https://www.adexchanger.com/online-advertising/google-chrome-will-drop-third-party-cookies-in-2-years/). Safest thing to do IMHO is to move away from cookies ASAP where they are used (sensibilizing business and management about it) and use some form of token authentication instead (JWT, OAuth, ..). This library was born for the sole purpose of wrapping a dying and cumbersome standard in a library, while retaining common features needed, so it can be dropped easily when not needed anymore.

### Android 12+
For the time being, until cookies die forever (for good), some solution will be useful for the people still on this technology. One maybe better way to deal with this (avoiding reflection problems you mentioned now and in the future) is to make a custom `Cookie` class internal to this library and use that instead for all the serialization/deserialization processes, converting it to common types where needed.

**Comment by gotev** [comment] 2022-03-20 18:01
Fixed in `1.5.0`

**Closed as completed by gotev** 2022-03-20 18:01 UTC
